import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
//import './globals.css'
import { dir } from 'i18next'
import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter' // or `v14-appRouter` if you are using Next.js v14
import StoreProvider from '../StoreProvider'
import { ThemeProviderContext } from '@/utils/ThemeContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'next-mui-kickstarter-ts',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  params: { lng },
}: {
  children: React.ReactNode
  params: { lng: string }
}) {
  return (
    <html lang={lng} dir={dir(lng)}>
      <body className={inter.className}>
        <StoreProvider>
          <AppRouterCacheProvider>
            <ThemeProviderContext>{children}</ThemeProviderContext>
          </AppRouterCacheProvider>
        </StoreProvider>
      </body>
    </html>
  )
}
